spring:
  application:
    name: JobSearch
  datasource:
    url: jdbc:h2:file:./data/jobsearch;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: ozodbek
    password: 2006
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  freemarker:
    expose-session-attributes: true
    expose-request-attributes: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ozodbekmamadzanov9@gmail.com
    password: kfnpfhvattmjaydn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090